"""initial_migration

Revision ID: 8a5dd4ce0c79
Revises: None
Create Date: 2026-05-29 11:28:34.932729

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a5dd4ce0c79'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_meta',
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(), nullable=True),
    sa.Column('roe', sa.Numeric(), nullable=True),
    sa.Column('eps', sa.Numeric(), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(), nullable=True),
    sa.Column('high_52w', sa.Numeric(), nullable=True),
    sa.Column('low_52w', sa.Numeric(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('users',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('plan', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('risk_profile', sa.String(length=20), server_default='moderate', nullable=False),
    sa.Column('preferred_sectors', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('investment_horizon', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=True),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channels', sa.ARRAY(sa.Text()), server_default='{push}', nullable=False),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_user_id'), 'backtest_runs', ['user_id'], unique=False)
    op.create_table('news_articles',
    sa.Column('ticker', sa.Text(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(), nullable=True),
    sa.Column('impact_level', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['stock_meta.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_articles_ticker'), 'news_articles', ['ticker'], unique=False)
    op.create_table('portfolios',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='INR', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), server_default='5', nullable=False),
    sa.Column('ml_score', sa.Numeric(), nullable=True),
    sa.Column('technical_score', sa.Numeric(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(), nullable=True),
    sa.Column('fundamental_score', sa.Numeric(), nullable=True),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['stock_meta.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_ticker'), 'predictions', ['ticker'], unique=False)
    op.create_table('suggestions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['stock_meta.ticker'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestions_user_id'), 'suggestions', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('avg_price', sa.Numeric(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_portfolio_id'), 'positions', ['portfolio_id'], unique=False)
    op.create_table('prediction_factors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('factor_type', sa.String(length=20), nullable=True),
    sa.Column('factor_name', sa.Text(), nullable=True),
    sa.Column('impact', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_factors_prediction_id'), 'prediction_factors', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_factors_prediction_id'), table_name='prediction_factors')
    op.drop_table('prediction_factors')
    op.drop_index(op.f('ix_positions_portfolio_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_suggestions_user_id'), table_name='suggestions')
    op.drop_table('suggestions')
    op.drop_index(op.f('ix_predictions_ticker'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_news_articles_ticker'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_backtest_runs_user_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stock_meta')
    # ### end Alembic commands ###
